apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitio-web
  template:
    metadata:
      labels:
        app: sitio-web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
        - name: sitio-web-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: sitio-web-volume
        persistentVolumeClaim:
          claimName: sitio-web-pvc
